_wandb:
    value:
        cli_version: 0.25.0
        e:
            8xy6b4z30hxiwjs1rlgl600wlijpvlw3:
                args:
                    - --tb-logdir
                    - /home/loop/isaac_sim-2023.1.1/OmniIsaacGymEnvs/runs/USV/Mar06_14-33-46/Mar06_14-34-15
                    - --entity
                    - loopzhang7-zhejiang-university
                    - --project
                    - OmniIsaacGymEnvs
                    - --run-name
                    - Mar06_14-34-15
                    - --strip-prefix
                    - auto
                    - --poll-interval
                    - "10"
                codePath: wandb_tb_rewrite_sync.py
                codePathLocal: wandb_tb_rewrite_sync.py
                cpu_count: 8
                cpu_count_logical: 16
                cudaVersion: "13.0"
                disk:
                    /:
                        total: "950045810688"
                        used: "234438672384"
                email: loopzhang7@163.com
                executable: /home/loop/anaconda3/envs/wandb_sync/bin/python
                git:
                    commit: 3ddc7da3a38a8c3edc71040fe0ca09d731f9556a
                    remote: git@github.com:loop-Z/omniisaacgymenvs_loop.git
                gpu: NVIDIA GeForce RTX 3070
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ampere
                      cudaCores: 5888
                      memoryTotal: "8589934592"
                      name: NVIDIA GeForce RTX 3070
                      uuid: GPU-4ea23ba7-d082-2615-d6a8-9a65c43ceaf9
                host: loop-ws
                memory:
                    total: "33583181824"
                os: Linux-6.8.0-100-generic-x86_64-with-glibc2.35
                program: /home/loop/isaac_sim-2023.1.1/OmniIsaacGymEnvs/wandb_tb_rewrite_sync.py
                python: CPython 3.10.19
                root: /home/loop/isaac_sim-2023.1.1/OmniIsaacGymEnvs
                startedAt: "2026-03-06T06:36:52.586394Z"
                writerId: 8xy6b4z30hxiwjs1rlgl600wlijpvlw3
        m: []
        python_version: 3.10.19
        t:
            "3":
                - 2
                - 13
                - 14
                - 16
                - 61
            "4": 3.10.19
            "5": 0.25.0
            "12": 0.25.0
            "13": linux-x86_64
include_prefixes:
    value:
        - Episode/
        - Loss/
        - rewards/
        - shaped_rewards/
        - episode_lengths/
        - Diagnostics/
        - Policy/
strip_prefix:
    value: Mar06_14-34-15/
tb_logdir:
    value: /home/loop/isaac_sim-2023.1.1/OmniIsaacGymEnvs/runs/USV/Mar06_14-33-46/Mar06_14-34-15
